CREATE TABLE PU_MEMBER (
    memberID VARCHAR(50) NOT NULL PRIMARY KEY,
    passwd VARCHAR(255) NOT NULL,
    memberType VARCHAR(20),
    active TINYINT
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PU_MEMBER_AUTHORITIES
(
	memberID  VARCHAR(100) NOT NULL,
	authority  VARCHAR(30) NULL
)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PU_MEMBER_AUTHORITIES ADD  PRIMARY KEY (memberID,authority);
